Repository Illuminator-team/Illuminator, pull requests merged in 2024-10, with the labels that each got.

#50 Improvements and extensions to the YAML simulation schema
  src/illuminator/schemas/__init__.py
  src/illuminator/schemas/simulation.example.yaml
  src/illuminator/schemas/simulation.py
  src/illuminator/schemas/validate_yaml.py
Labels: enhancement

#51 Enhance validation of simulation schema
  src/illuminator/schemas/simulation.example.yaml
  src/illuminator/schemas/simulation.py
Labels: enhancement

#53 Clean up
  examples/builder_model_example.py
  examples/mosaik_sim_config.py
  examples/simulation.example.yaml
  illuminator-config.yaml
  illuminator.yaml
  simple_test.py
  simulation creator_DNcontrolCase.py
  simulation creator_games.py
  simulation creator_multienergyCase.py
  simulation creator_residentialcase.py
  src/illuminator/builder/scenario_schema.py
  src/illuminator/engine/__init__.py
  src/illuminator/engine/collector.py
  src/illuminator/engine/main.py
  src/illuminator/engine/state_space_simulator.py
  src/illuminator/engine/yaml_interpreter.py
  src/illuminator/schemas/config.yaml
  src/illuminator/schemas/simulation.py
  tests/core/test_builder_model.py
  yaml.py
Labels: FAIR software

#59 Contributors
  readme.md
Labels: FAIR software

#62 Example Generate documentation from doc strings
  docs/conf.py
  docs/index.rst
  docs/references/models.rst
Labels: documentation

#55 Documentation: First part of model documentation.
  Controllers/ResidentialController/controller_mosaik.py
  src/illuminator/models/Battery/battery_model.py
  src/illuminator/models/Battery/battery_mosaik.py
  src/illuminator/models/Controller/controller_model.py
  src/illuminator/models/Controller/controller_mosaik.py
  src/illuminator/models/Eboiler/eboiler_model.py
  src/illuminator/models/Eboiler/eboiler_model_old.py
  src/illuminator/models/Eboiler/eboiler_mosaik.py
  src/illuminator/models/EleDisNetworkSim/network.py
  src/illuminator/models/Electrolyser/electrolyser_model.py
  src/illuminator/models/Electrolyser/electrolyser_mosaik.py
  src/illuminator/models/Elenetwork/electricity_network_model.py
  src/illuminator/models/Elenetwork/electricity_network_mosaik.py
Labels: documentation

#56 Documentation: Fuel to Heat product models
  Agents/prosumer_model.py
  src/illuminator/models/Fuelcell/fuelcell_model.py
  src/illuminator/models/Fuelcell/fuelcell_mosaik.py
  src/illuminator/models/H2demand/h2demand_model.py
  src/illuminator/models/H2demand/h2demand_mosaik.py
  src/illuminator/models/H2network/gas_network_model.py
  src/illuminator/models/H2network/gas_network_mosaik.py
  src/illuminator/models/H2product/h2product_model.py
  src/illuminator/models/H2product/h2product_mosaik.py
  src/illuminator/models/H2storage/h2storage_model.py
  src/illuminator/models/H2storage/h2storage_mosaik.py
  src/illuminator/models/Heatdemand/qdemand_model.py
  src/illuminator/models/Heatdemand/qdemand_mosaik.py
  src/illuminator/models/Heatnetwork/heat_network_model.py
  src/illuminator/models/Heatnetwork/heat_network_mosaik.py
  src/illuminator/models/Heatproduct/qproduct_model.py
  src/illuminator/models/Heatproduct/qproduct_mosaik.py
Labels: documentation

#57 Documentation: rest of the dostrings heatpump rest
  Agents/prosumer_mosaik.py
  Controllers/GPController/gpcontroller_model.py
  Controllers/GPController/gpcontroller_mosaik.py
  src/illuminator/models/Heatpump/controller/controller.py
  src/illuminator/models/Heatpump/controller/controller_mosaik.py
  src/illuminator/models/Heatpump/heatpump/Heat_Pump_Des.py
  src/illuminator/models/Heatpump/heatpump/Heat_Pump_Model.py
  src/illuminator/models/Heatpump/heatpump/Heat_Pump_mosaik.py
  src/illuminator/models/Heatpump/hotwatertanksim/hotwatertank.py
  src/illuminator/models/Heatpump/hotwatertanksim/hotwatertank_mosaik.py
  src/illuminator/models/Heatstorage/qstorage_model.py
  src/illuminator/models/Heatstorage/qstorage_mosaik.py
  src/illuminator/models/Hotwaterstorage/hotwaterstorage_model.py
  src/illuminator/models/Hotwaterstorage/hotwaterstorage_mosaik.py
  src/illuminator/models/Load/load_model.py
  src/illuminator/models/Load/load_mosaik.py
  src/illuminator/models/LoadinNetSim/example/collector.py
  src/illuminator/models/LoadinNetSim/example/loadmodel.py
  src/illuminator/models/LoadinNetSim/example/model_mosaikapi.py
  src/illuminator/models/LoadinNetSim/example/read_csv.py
  src/illuminator/models/LoadinNetSim/model.py
  src/illuminator/models/LoadinNetSim/mosaik-model.py
  src/illuminator/models/PV/pv_model.py
  src/illuminator/models/PV/pv_model_new.py
  src/illuminator/models/PV/pv_mosaik.py
  src/illuminator/models/Valves/h2valve_model.py
  src/illuminator/models/Valves/h2valve_mosaik.py
  src/illuminator/models/Valves/qvalve_model.py
  src/illuminator/models/Valves/qvalve_mosaik.py
  src/illuminator/models/Wind/Wind_model.py
  src/illuminator/models/Wind/wind_mosaik.py
  src/illuminator/models/collector.py
  src/illuminator/models/influxdbwriter.py
  src/illuminator/models/mosaik_csv.py
  src/illuminator/models/mosaik_sql.py
  src/illuminator/models/mqttsend.py
  src/illuminator/models/submqtt.py
  src/illuminator/models/test_model.py
Labels: documentation
