Repository Illuminator-team/Illuminator, pull requests merged in 2024-09, with the labels that each got.

#20 Documentation/doc strings
  .gitignore
  Agents/prosumer_S_model.py
  Agents/prosumer_model.py
  Agents/prosumer_mosaik.py
  Controllers/GPController/gpcontroller_model.py
  DEPRECATED - environment_macosarm64.yml
  DEPRECATED - environment_windows.yml
  configuration/bids/flex_trade.py
  configuration/bids/make_bids.py
  configuration/bids/plot_bids.py
  environment_full.yml
  simulation creator_DNcontrolCase.py
  simulation creator_multienergyCase.py
Labels: documentation

#31 Documentation for the Controllers folder + minor detail for previous docstrings
  Agents/prosumer_S_model.py
  Agents/prosumer_model.py
  Agents/prosumer_mosaik.py
  Controllers/GPController/gpcontroller_model.py
  Controllers/GPController/gpcontroller_mosaik.py
  Controllers/NetVoltageControllerSim/controller.py
  Controllers/NetVoltageControllerSim/mosaik-model.py
  Controllers/ResidentialController/controller_model.py
  Controllers/ResidentialController/controller_mosaik.py
  Games/emarket_model.py
  Games/emarket_mosaik.py
  Games/p2ptrading_model.py
  Games/p2ptrading_mosaik.py
  Games/rtprice_model.py
  Games/rtprice_mosaik.py
  configuration/bids/make_bids.py
  configuration/bids/plot_bids.py
Labels: documentation

#32 Development workflow
  CONTRIBUTING.md
  docs/_static/img/illuminator-workflow.png
  environment.yml
  illuminator.yaml
  yaml.py
Labels: documentation

#35 Update readme file
  CONTRIBUTING.md
  readme.md
Labels: documentation

#28 A YAML file for configuring simulations
  configs/__init__.py
  configs/modelling-example.yaml
  configs/modelling_schema.py
  configs/parser.py
  environment.yml
  illuminator-config.yaml
  simple_test.py
Labels: enhancement

#40 Clean up
  Models/example_illuminator_2/battery.yaml
  Models/example_illuminator_2/illuminator_battery.py
  Models/example_illuminator_2/mosaik_battery.py
Labels: enhancement

#41 Add a state space model template
  Models/example_illuminator_2/state_space_model.py
  Models/example_illuminator_2/state_space_simulator.py
Labels: enhancement

#44 First version of illuminator model interface
  Models/construct_model.py
Labels: enhancement, question
