Repository Illuminator-team/Illuminator, pull requests merged in 2024-11, with the labels that each got.

#63 Added unit tests for the PV model and mosaik classes
  tests/Models/PV/test_pv_model.py
  tests/Models/PV/test_pv_mosaik.py
Labels: tests

#67 Update dev's documentation
  CONTRIBUTING.md
  docs/developer/start.md
  docs/index.rst
  docs/references/engine-api.rst
  pyproject.toml
  src/illuminator/cli/main.py
  src/illuminator/engine.py
  src/illuminator/engine/__init__.py
  tests/data/data.csv
  tests/schemas/test_simulation.py
  tests/test_engine.py
Labels: documentation

#68 Add tutorial example
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
  docs/turotials/example.ipynb
  pyproject.toml
Labels: documentation

#69 Fixe missing dependencies in action
  .github/workflows/deploy-docs.yml
  docs/requirements.txt
Labels: bug, documentation

#72 Updates to packaging metadata
  CHANGELOG.md
  pyproject.toml
Labels: documentation

#73 Fixes to unit tests
  src/illuminator/models/__init__.py
  tests/models/test_pv_model.py
  tests/models/test_pv_mosaik.py
Labels: bug

#74 Added testing and docstring documentation.
  CONTRIBUTING.md
  docs/Illuminator Model Classification.xlsx
  docs/_static/img/testing_pyramid.jpg
  docs/developer/developer-docstrings.md
  docs/developer/testing-explained.md
  docs/developer/writing-tests.md
  docs/index.rst
  docs/references/models.rst
  docs/tutorials/example.ipynb
Labels: documentation

#76 Update deploy-docs.yml
  .github/workflows/deploy-docs.yml
Labels: enhancement

#77 Update pyproject.toml
  pyproject.toml
Labels: bug, documentation

#78 Update pyproject.toml
  pyproject.toml
Labels: documentation

#79 Version 3.0.0-alpha.1
  docs/cluster-setup.md
  docs/index.rst
  docs/quick-start.md
  environment.yml
  examples/example_illuminator_2/adder_model.py
  examples/example_illuminator_2/multiplier_model.py
  examples/example_illuminator_2/state_space_simulator.py
  pyproject.toml
  src/illuminator/builder/model.py
  src/illuminator/cli/main.py
  src/illuminator/engine.py
  src/illuminator/models/__init__.py
  src/illuminator/models/adder.py
  tests/data/solar-sample.csv
Labels: bug

#64 Update to the cluster Pi code
  configuration/build_runshfile.py
  configuration/modelling-example.yaml
  configuration/parse_yaml.py
  configuration/run.sh
  readme.md
Labels: documentation, enhancement

#81 Documentation and Interfaces
  docs/cluster-setup.md
  docs/conf.py
  docs/developer/set-up.md
  docs/index.rst
  docs/user/depricated-user-guide.md
  docs/user/start.md
  examples/adder.yaml
  examples/adder_model.py
  examples/builder_model_example.py
  pyproject.toml
  src/illuminator/builder/model.py
  src/illuminator/cli/main.py
  src/illuminator/cli/state_space_simulator.py
  src/illuminator/cluster/__init__.py
  src/illuminator/engine.py
  src/illuminator/schema/__init__.py
  src/illuminator/schema/config.yaml
  src/illuminator/schema/scenario_data.csv
  src/illuminator/schema/simulation.example.yaml
  src/illuminator/schema/simulation.py
  src/illuminator/schemas/validate_yaml.py
  tests/test_engine.py
Labels: bug, documentation, enhancement

#82 Missing build_runshfile
  docs/cluster-setup.md
  docs/user/config-file.md
  src/illuminator/cluster/build_runshfile.py
  src/illuminator/schema/simulation.py
  tests/schema/scenario.example.yaml
  tests/schema/test_simulation.py
  tests/schemas/schema.example.yaml
  tests/schemas/test_simulation.py
  tests/test_engine.py
Labels: bug, documentation

#84 Fixes to bugs resulting from removing `results` from YAML file
  docs/user/config-file.md
  readme.md
  src/illuminator/cli/main.py
  src/illuminator/cluster/build_runshfile.py
  src/illuminator/engine.py
  src/illuminator/schema/simulation.py
Labels: bug, documentation

#85 Add Python interface
  docs/index.rst
  docs/user/simulations.md
  src/illuminator/cli/main.py
  src/illuminator/engine.py
Labels: documentation, enhancement

#86 Hotfix collection for ModelConstructor class
  examples/adder_copy.yaml
  src/illuminator/builder/model.py
  src/illuminator/cli/main.py
  src/illuminator/engine.py
  src/illuminator/schema/simulation.py
Labels: bug, enhancement

#88 Improvements and hot fixes for version 3.0.0-alpha2
  configuration/build_runshfile.py
  configuration/modelling-example.yaml
  configuration/parse_yaml.py
  configuration/run.sh
  docs/cluster-setup.md
  docs/conf.py
  docs/developer/set-up.md
  docs/index.rst
  docs/user/config-file.md
  docs/user/depricated-user-guide.md
  docs/user/simulations.md
  docs/user/start.md
  examples/adder.yaml
  examples/adder_copy.yaml
  examples/adder_model.py
  examples/builder_model_example.py
  pyproject.toml
  readme.md
  src/illuminator/builder/model.py
  src/illuminator/cli/main.py
  src/illuminator/cli/state_space_simulator.py
  src/illuminator/cluster/__init__.py
  src/illuminator/cluster/build_runshfile.py
  src/illuminator/engine.py
  src/illuminator/schema/__init__.py
  src/illuminator/schema/config.yaml
  src/illuminator/schema/scenario_data.csv
  src/illuminator/schema/simulation.example.yaml
  src/illuminator/schema/simulation.py
  src/illuminator/schemas/validate_yaml.py
  tests/schema/scenario.example.yaml
  tests/schema/test_simulation.py
  tests/schemas/schema.example.yaml
  tests/schemas/test_simulation.py
  tests/test_engine.py
Labels: bug, documentation, enhancement

#91 Models with time shifts
  docs/references/engine-api.rst
  docs/user/config-file.md
  examples/adder.yaml
  examples/adder_copy.yaml
  examples/adder_model.py
  examples/python_api.py
  examples/simulation.example.yaml
  simple_test2.yaml
  src/illuminator/builder/model.py
  src/illuminator/engine.py
  src/illuminator/models/Battery/battery_mosaik.py
  src/illuminator/models/adder.py
Labels: documentation, enhancement
